(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VA starship, starcraft or interstellar spacecraft is a theoretical spacecraft designed for traveling between planetary systems, as opposed to a vehicle designed for orbital spaceflight or interplanetary travel.The term is mostly found in science fiction, because such craft have never been constructed. Some cite the first use of the word in Oahspe: A New Bible (1882).Whilst the Voyager and Pioneer probes have travelled into local interstellar space, the purpose of these unmanned craft was specifically interplanetary and they are not predicted to reach another star system (although Voyager 1 will travel to within 1.7 light years of AC +79 3888 in approximately 40,000 years). Several preliminary designs for starships have been undertaken through exploratory engineering, using feasibility studies with modern technology or technology thought likely to be available in the near future.In April 2016, scientists announced Breakthrough Starshot, a Breakthrough Initiatives program, to develop a proof-of-concept fleet of small centimeter-sized light sail spacecraft, named StarChip, capable of making the journey to Alpha Centauri, the nearest extrasolar star system, at speeds of 20% and 15% of the speed of light, taking between 20 and 30 years to reach the star system, respectively, and about 4 years to notify Earth of a successful arrival.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/wikiPageExtracted
p32
ssg8
(dp33
Vdatatype
p34
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p35
sVtype
p36
Vtyped-literal
p37
sVvalue
p38
V2016-11-06T07:53:57Z
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/wikiPageLength
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V11476
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/wikiPageModified
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V2016-10-31T21:29:47Z
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/wikiPageOutDegree
p71
ssg8
(dp72
Vdatatype
p73
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p74
sVtype
p75
Vtyped-literal
p76
sVvalue
p77
V138
p78
ssasVordered
p79
I01
ss.