(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VAsterix or The Adventures of Asterix (French: Astérix or Astérix le Gaulois, IPA: [aste\u0281iks l\u0259 \u0261olwa]) is a series of French comics. The series first appeared in the Franco-Belgian comics magazine Pilote on 29 October 1959. It was written by René Goscinny and illustrated by Albert Uderzo until the death of Goscinny in 1977. Uderzo then took over the writing until 2009, when he sold the rights to publishing company Hachette. As of 2015, 36 volumes have been released.The series follows the exploits of a village of indomitable Gauls as they resist Roman occupation. They do so by means of a magic potion brewed by their druid, named Getafix in the English translations, which temporarily gives the recipient superhuman strength. The protagonist, the titular character Asterix, along with his friend Obelix have various adventures. The "ix" ending of both names (as well as all the other pseudo-Gaulish "ix" names in the series) alludes to the "rix" suffix (meaning "king") present in the names of many real Gaulish chieftains such as Vercingetorix, Orgetorix, and Dumnorix. (See below for further explanations of the character names.) Many of the stories have them travel to foreign countries, though others are set in and around their village. For much of the history of the series (Volumes 4 through 29), settings in Gaul and abroad alternated, with even-numbered volumes set abroad and odd-numbered volumes set in Gaul, mostly in the village.The Asterix series is one of the most popular Franco-Belgian comics in the world, with the series being translated into over 100 languages, and it is popular in most European countries.The success of the series has led to the adaptation of several books into 13 films: nine animated, and four live action. There have also been a number of games based on the characters, and a theme park near Paris, Parc Astérix. As of October 2009, 325 million copies of 34 Asterix books had been sold worldwide, making co-creators René Goscinny and Albert Uderzo France's bestselling authors abroad.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/wikiPageExtracted
p32
ssg8
(dp33
Vdatatype
p34
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p35
sVtype
p36
Vtyped-literal
p37
sVvalue
p38
V2016-10-27T18:28:51Z
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/wikiPageLength
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V41721
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/wikiPageModified
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V2016-10-27T16:56:46Z
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/wikiPageOutDegree
p71
ssg8
(dp72
Vdatatype
p73
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p74
sVtype
p75
Vtyped-literal
p76
sVvalue
p77
V296
p78
ssasVordered
p79
I01
ss.