(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VCharles II (29 May 1630 \u2013 6 February 1685) was king of England, Scotland, and Ireland.Charles II's father, Charles I, was executed at Whitehall on 30 January 1649, at the climax of the English Civil War. Although the Parliament of Scotland proclaimed Charles II King on 5 February 1649, England entered the period known as the English Interregnum or the English Commonwealth, and the country was a de facto republic, led by Oliver Cromwell. Cromwell defeated Charles II at the Battle of Worcester on 3 September 1651, and Charles fled to mainland Europe. Cromwell became virtual dictator of England, Scotland and Ireland, and Charles spent the next nine years in exile in France, the Dutch Republic, and the Spanish Netherlands.A political crisis that followed the death of Cromwell in 1658 resulted in the restoration of the monarchy, and Charles was invited to return to Britain. On 29 May 1660, his 30th birthday, he was received in London to public acclaim. After 1660, all legal documents were dated as if he had succeeded his father as king in 1649.Charles's English parliament enacted laws known as the Clarendon Code, designed to shore up the position of the re-established Church of England. Charles acquiesced to the Clarendon Code even though he favoured a policy of religious tolerance. The major foreign policy issue of his early reign was the Second Anglo-Dutch War. In 1670, he entered into the secret treaty of Dover, an alliance with his first cousin King Louis XIV of France. Louis agreed to aid him in the Third Anglo-Dutch War and pay him a pension, and Charles secretly promised to convert to Catholicism at an unspecified future date. Charles attempted to introduce religious freedom for Catholics and Protestant dissenters with his 1672 Royal Declaration of Indulgence, but the English Parliament forced him to withdraw it. In 1679, Titus Oates's revelations of a supposed "Popish Plot" sparked the Exclusion Crisis when it was revealed that Charles's brother and heir (James, Duke of York) was a Catholic. The crisis saw the birth of the pro-exclusion Whig and anti-exclusion Tory parties. Charles sided with the Tories, and, following the discovery of the Rye House Plot to murder Charles and James in 1683, some Whig leaders were executed or forced into exile. Charles dissolved the English Parliament in 1681, and ruled alone until his death on 6 February 1685. He was received into the Roman Catholic Church on his deathbed.Charles was popularly known as the Merry Monarch, in reference to both the liveliness and hedonism of his court and the general relief at the return to normality after over a decade of rule by Cromwell and the Puritans. Charles's wife, Catherine of Braganza, bore no live children, but Charles acknowledged at least twelve illegitimate children by various mistresses. He was succeeded by his brother James.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VCharles II (29 May 1630 \u2013 6 February 1685) was king of England, Scotland, and Ireland. He was king of Scotland from 1649 until his deposition in 1651, and king of England, Scotland, and Ireland from the restoration of the monarchy in 1660 until his death.Charles II's father, Charles I, was executed at Whitehall on 30 January 1649, at the climax of the English Civil War. Although the Parliament of Scotland proclaimed Charles II King on 5 February 1649, England entered the period known as the English Interregnum or the English Commonwealth, and the country was a de facto republic, led by Oliver Cromwell. Cromwell defeated Charles II at the Battle of Worcester on 3 September 1651, and Charles fled to mainland Europe. Cromwell became virtual dictator of England, Scotland and Ireland, and Charles spent the next nine years in exile in France, the Dutch Republic, and the Spanish Netherlands. A political crisis that followed the death of Cromwell in 1658 resulted in the restoration of the monarchy, and Charles was invited to return to Britain. On 29 May 1660, his 30th birthday, he was received in London to public acclaim. After 1660, all legal documents were dated as if he had succeeded his father as king in 1649.Charles's English parliament enacted laws known as the Clarendon Code, designed to shore up the position of the re-established Church of England. Charles acquiesced to the Clarendon Code even though he favoured a policy of religious tolerance. The major foreign policy issue of his early reign was the Second Anglo-Dutch War. In 1670, he entered into the secret treaty of Dover, an alliance with his first cousin King Louis XIV of France. Louis agreed to aid him in the Third Anglo-Dutch War and pay him a pension, and Charles secretly promised to convert to Catholicism at an unspecified future date. Charles attempted to introduce religious freedom for Catholics and Protestant dissenters with his 1672 Royal Declaration of Indulgence, but the English Parliament forced him to withdraw it. In 1679, Titus Oates's revelations of a supposed "Popish Plot" sparked the Exclusion Crisis when it was revealed that Charles's brother and heir (James, Duke of York) was a Catholic. The crisis saw the birth of the pro-exclusion Whig and anti-exclusion Tory parties. Charles sided with the Tories, and, following the discovery of the Rye House Plot to murder Charles and James in 1683, some Whig leaders were executed or forced into exile. Charles dissolved the English Parliament in 1681, and ruled alone until his death on 6 February 1685. He was received into the Roman Catholic Church on his deathbed.Charles was popularly known as the Merry Monarch, in reference to both the liveliness and hedonism of his court and the general relief at the return to normality after over a decade of rule by Cromwell and the Puritans. Charles's wife, Catherine of Braganza, bore no live children, but Charles acknowledged at least twelve illegitimate children by various mistresses. He was succeeded by his brother James.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/activeYearsEndYear
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#gYear
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V1660
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/activeYearsStartYear
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#gYear
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V1660
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/birthDate
p71
ssg8
(dp72
Vdatatype
p73
Vhttp://www.w3.org/2001/XMLSchema#date
p74
sVtype
p75
Vtyped-literal
p76
sVvalue
p77
V1630-05-29
p78
ssa(dp79
g7
(dp80
Vtype
p81
Vuri
p82
sVvalue
p83
Vhttp://dbpedia.org/ontology/deathDate
p84
ssg8
(dp85
Vdatatype
p86
Vhttp://www.w3.org/2001/XMLSchema#date
p87
sVtype
p88
Vtyped-literal
p89
sVvalue
p90
V1685-02-06
p91
ssa(dp92
g7
(dp93
Vtype
p94
Vuri
p95
sVvalue
p96
Vhttp://dbpedia.org/ontology/wikiPageExtracted
p97
ssg8
(dp98
Vdatatype
p99
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p100
sVtype
p101
Vtyped-literal
p102
sVvalue
p103
V2016-10-28T21:27:19Z
p104
ssa(dp105
g7
(dp106
Vtype
p107
Vuri
p108
sVvalue
p109
Vhttp://dbpedia.org/ontology/wikiPageLength
p110
ssg8
(dp111
Vdatatype
p112
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p113
sVtype
p114
Vtyped-literal
p115
sVvalue
p116
V61962
p117
ssa(dp118
g7
(dp119
Vtype
p120
Vuri
p121
sVvalue
p122
Vhttp://dbpedia.org/ontology/wikiPageModified
p123
ssg8
(dp124
Vdatatype
p125
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p126
sVtype
p127
Vtyped-literal
p128
sVvalue
p129
V2016-10-25T18:59:07Z
p130
ssa(dp131
g7
(dp132
Vtype
p133
Vuri
p134
sVvalue
p135
Vhttp://dbpedia.org/ontology/wikiPageOutDegree
p136
ssg8
(dp137
Vdatatype
p138
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p139
sVtype
p140
Vtyped-literal
p141
sVvalue
p142
V476
p143
ssasVordered
p144
I01
ss.