(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VThe Ganz UV (Hungarian pronunciation: [\u0261\u0252\u014bz \u02c8u\u02d0ve\u02d0]) is a series of tramcars which was manufactured by Hungarian companies Ganz Vagon- és Gépgyár ("Ganz Carriage and Machine Factory"), Rába Magyar Vagon- és Gépgyár ("Rába Hungarian Carriage and Machine Factory") and Klement Gottwald Villamossági Gyár ("Klement Gottwald Electric Factory"), which was the name of Ganz Villamossági Gyár ("Ganz Electric Factory") at the time of manufacturing. The UV tramcars have four main variants, all are four axle rail motor coaches with a Bo'Bo'tr axle arrangement, capable of operating as electric multiple units. The cars were manufactured between 1956 and 1965 in Budapest, and overall 375 regular units and 2 prototypes were made.The UV type designation resolves to U típusú távvezérelt motorkocsi ("type U remotely controlled motor coach"). The units are capable of controlling another unit of their type through proprietary 50-wire cables. The trams are also capable of sensing the breakup of the tramset with the use of a chain hanging between the cars; brakes are automatically applied if a chain is pulled out from its sockets. Two prototypes were made with aluminium carbodies, designated as UZ, these proved to be unsuccessful. In addition, in the 1990s, 20 UV cars were refurbished and they are referred to as MUV (modernizált UV, "modernized UV"). Planned to replace the pre-WWII design TM trams, with 377 units, the UV series became the most numerous type of tramcar produced in Hungary.The first car entered passenger service in 1956, and the type was ultimately decommissioned in 2007, after roughly 51 years of continuous service. UV trams became one of the symbols of Budapest, and had appeared in a number of Hungarian and foreign movies as plot elements. Two preserved, paired UV cars now annually serve as the city's so-called Christmas light trams in the festive season, decorated with white and blue LED lights.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VThe Ganz UV (Hungarian pronunciation: [\u02c8\u0261\u0252nz \u02c8u\u02d0ve\u02d0]) is a series of tramcars which was manufactured by Hungarian companies Ganz Vagon- és Gépgyár ("Ganz Carriage and Machine Factory"), Rába Magyar Vagon- és Gépgyár ("Rába Hungarian Carriage and Machine Factory") and Klement Gottwald Villamossági Gyár ("Klement Gottwald Electric Factory"), which was the name of Ganz Villamossági Gyár ("Ganz Electric Factory") at the time of manufacturing. The UV tramcars have four main variants, all are four axle rail motor coaches with a Bo'Bo'tr axle arrangement, capable of operating as electric multiple units. The cars were manufactured between 1956 and 1965 in Budapest, and overall 375 regular units and 2 prototypes were made.The UV type designation resolves to U típusú távvezérelt motorkocsi ("type U remotely controlled motor coach"). The units are capable of controlling another unit of their type through proprietary 50-wire cables. The trams are also capable of sensing the breakup of the tramset with the use of a chain hanging between the cars; brakes are automatically applied if a chain is pulled out from its sockets. Two prototypes were made with aluminium carbodies, designated as UZ, these proved to be unsuccessful. In addition, in the 1990s, 20 UV cars were refurbished and they are referred to as MUV (modernizált UV, "modernized UV"). Planned to replace the pre-WWII design TM trams, with 377 units, the UV series became the most numerous type of tramcar produced in Hungary.The first car entered passenger service in 1956, and the type was ultimately decommissioned in 2007, after roughly 51 years of continuous service. UV trams became one of the symbols of Budapest, and had appeared in a number of Hungarian and foreign movies as plot elements. Two preserved, paired UV cars now annually serve as the city's so-called Christmas light trams in the festive season, decorated with white and blue LED lights.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/wikiPageExtracted
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V2016-10-30T19:37:22Z
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/wikiPageLength
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V10915
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/wikiPageModified
p71
ssg8
(dp72
Vdatatype
p73
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p74
sVtype
p75
Vtyped-literal
p76
sVvalue
p77
V2016-09-12T16:38:44Z
p78
ssa(dp79
g7
(dp80
Vtype
p81
Vuri
p82
sVvalue
p83
Vhttp://dbpedia.org/ontology/wikiPageOutDegree
p84
ssg8
(dp85
Vdatatype
p86
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p87
sVtype
p88
Vtyped-literal
p89
sVvalue
p90
V57
p91
ssasVordered
p92
I01
ss.