(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VMrs. (American English) or Mrs (British English) (Standard English pronunciation /\u02c8m\u026as\u1d7bz/) is a commonly used English honorific used for women, usually for those who are married and who do not instead use another title (or rank), such as Dr, Professor, Ms., President, Dame, Prime Minister, etc. In most Commonwealth countries, a full stop (period) is usually not used with the title. In the United States and Canada a period is usually used (see Abbreviation).Mrs originated as a contraction of the honorific Mistress, the feminine of Mister, or Master, which was originally applied to both married and unmarried women. The split into Mrs for married women and Miss for unmarried began during the 17th century; the 20th century saw the coinage of a new unmarked option Ms.It is rare for Mrs to be written in a non-abbreviated form, and the unabbreviated word lacks a standard spelling. In literature it may appear as missus or missis in dialogue. A variant in the works of Thomas Hardy and others is "Mis'ess", reflecting its etymology. Misses has been used but is ambiguous, as this is a commonly used plural for Miss.The plural of Mrs is from the French: Mesdames. This may be used as-is in written correspondence, or it may be abbreviated Mmes.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/wikiPageExtracted
p32
ssg8
(dp33
Vdatatype
p34
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p35
sVtype
p36
Vtyped-literal
p37
sVvalue
p38
V2016-11-03T11:46:02Z
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/wikiPageLength
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V6608
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/wikiPageModified
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V2016-10-28T10:02:54Z
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/wikiPageOutDegree
p71
ssg8
(dp72
Vdatatype
p73
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p74
sVtype
p75
Vtyped-literal
p76
sVvalue
p77
V47
p78
ssasVordered
p79
I01
ss.