(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VOklahoma /\u02cco\u028akl\u0259\u02c8ho\u028am\u0259/ (Cherokee: Asgaya gigageyi / \u13a0\u13cd\u13a6\u13ef \u13a9\u13a6\u13a8\u13f1; or transliterated from English as \u13a3\u13a6\u13b3\u13b0\u13b9 (ò\u0261àlàhoma), Pawnee: Uukuhuúwa, Cayuga: Gahnawiyo\u02c0geh) is a state located in the South Central United States. Oklahoma is the 20th most extensive and the 28th most populous of the 50 United States. The state's name is derived from the Choctaw words okla and humma, meaning "red people". It is also known informally by its nickname, The Sooner State, in reference to the non-Native settlers who staked their claims on the choicest pieces of land before the official opening date, and the Indian Appropriations Act of 1889, which opened the door for white settlement in America's Indian Territory. The name was settled upon statehood, Oklahoma Territory and Indian Territory were merged and Indian was dropped from the name. On November 16, 1907, Oklahoma became the 46th state to enter the union. Its residents are known as Oklahomans, or informally "Okies", and its capital and largest city is Oklahoma City.A major producer of natural gas, oil, and agricultural products, Oklahoma relies on an economic base of aviation, energy, telecommunications, and biotechnology. In 2007, it had one of the fastest-growing economies in the United States, ranking among the top states in per capita income growth and gross domestic product growth. Oklahoma City and Tulsa serve as Oklahoma's primary economic anchors, with nearly two-thirds of Oklahomans living within their metropolitan statistical areas.With small mountain ranges, prairie, mesas, and eastern forests, most of Oklahoma lies in the Great Plains, Cross Timbers and the U.S. Interior Highlands\u2014a region especially prone to severe weather. In addition to having a prevalence of English, German, Scottish, Scotch-Irish, and Native American ancestry, more than 25 Native American languages are spoken in Oklahoma, second only to California.Oklahoma is located on a confluence of three major American cultural regions and historically served as a route for cattle drives, a destination for southern settlers, and a government-sanctioned territory for Native Americans.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VOklahoma /\u02cco\u028akl\u0259\u02c8ho\u028am\u0259/ (Cherokee: Asgaya gigageyi / \u13a0\u13cd\u13a6\u13ef \u13a9\u13a6\u13a8\u13f1; or transliterated from English as \u13a3\u13a6\u13b3\u13b0\u13b9 (ò\u0261àlàhoma), Pawnee: Uukuhuúwa, Cayuga: Gahnawiyo\u02c0geh) is a state located in the South Central United States. Oklahoma is the 20th-most extensive and the 28th-most populous of the 50 United States. The state's name is derived from the Choctaw words okla and humma, meaning "red people". It is also known informally by its nickname, The Sooner State, in reference to the non-Native settlers who staked their claims on the choicest pieces of land before the official opening date, and the Indian Appropriations Act of 1889, which opened the door for white settlement in America's Indian Territory. The name was settled upon statehood, Oklahoma Territory and Indian Territory were merged and Indian was dropped from the name. On November 16, 1907, Oklahoma became the 46th state to enter the union. Its residents are known as Oklahomans, or informally "Okies", and its capital and largest city is Oklahoma City.A major producer of natural gas, oil, and agricultural products, Oklahoma relies on an economic base of aviation, energy, telecommunications, and biotechnology. In 2007, it had one of the fastest-growing economies in the United States, ranking among the top states in per capita income growth and gross domestic product growth. Oklahoma City and Tulsa serve as Oklahoma's primary economic anchors, with nearly two-thirds of Oklahomans living within their metropolitan statistical areas.With small mountain ranges, prairie, mesas, and eastern forests, most of Oklahoma lies in the Great Plains, Cross Timbers and the U.S. Interior Highlands\u2014a region especially prone to severe weather. In addition to having a prevalence of English, German, Scottish, Scotch-Irish, and Native American ancestry, more than 25 Native American languages are spoken in Oklahoma, second only to California.Oklahoma is located on a confluence of three major American cultural regions and historically served as a route for cattle drives, a destination for southern settlers, and a government-sanctioned territory for Native Americans.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/wikiPageExtracted
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V2016-11-04T01:47:25Z
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/wikiPageLength
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V174063
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/wikiPageModified
p71
ssg8
(dp72
Vdatatype
p73
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p74
sVtype
p75
Vtyped-literal
p76
sVvalue
p77
V2016-10-31T13:41:09Z
p78
ssa(dp79
g7
(dp80
Vtype
p81
Vuri
p82
sVvalue
p83
Vhttp://dbpedia.org/ontology/wikiPageOutDegree
p84
ssg8
(dp85
Vdatatype
p86
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p87
sVtype
p88
Vtyped-literal
p89
sVvalue
p90
V855
p91
ssasVordered
p92
I01
ss.