(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VAmherst College (/\u02c8æm\u0259rst/ AM-\u0259rst) is a private liberal arts college located in Amherst, Massachusetts, United States. Founded in 1821 as an attempt to relocate Williams College by its president, Zephaniah Swift Moore, Amherst is the third oldest institution of higher education in Massachusetts. The institution was named after the town, which in turn had been named after Lord Jeffery Amherst. Amherst was established as a men's college and became coeducational in 1975.Amherst is an exclusively undergraduate four-year institution and enrolled 1,795 students in the fall of 2015. Students choose courses from 38 major programs in an open curriculum. Students are not required to study a core curriculum or fulfill any distribution requirements and may even design their own unique interdisciplinary major. Freshmen may take advanced courses, and seniors may take introductory ones. For the class of 2020, Amherst received 8,397 applications and accepted 1,149 yielding a 13.7% acceptance rate. Amherst was ranked as the second best liberal arts college in the country by U.S. News & World Report, and 12th out of all U.S. colleges and universities by Forbes in their 2016 rankings. Amherst competes in the New England Small College Athletic Conference.Amherst has historically had close relationships and rivalries with Williams College and Wesleyan University which form the Little Three colleges. The college is a member of the Five Colleges consortium, which allows its students to attend classes at four other Pioneer Valley institutions. These include Mount Holyoke College, Smith College, Hampshire College, and the University of Massachusetts Amherst.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VAmherst College (/\u02c8æm\u0259rst/ AM-\u0259rst) is a private liberal arts college located in Amherst, Massachusetts, United States. Founded in 1821 as an attempt to relocate Williams College by its president, Zephaniah Swift Moore, Amherst is the third oldest institution of higher education in Massachusetts. The institution was named after the town, which in turn had been named after Lord Jeffery Amherst. Amherst was established as a men's college and became coeducational in 1975.Amherst is an exclusively undergraduate four-year institution and enrolled 1,795 students in the fall of 2015. Students choose courses from 38 major programs in an open curriculum. Students are not required to study a core curriculum or fulfill any distribution requirements and may even design their own unique interdisciplinary major. Freshmen may take advanced courses, and seniors may take introductory ones. For the class of 2020, Amherst received 8,397 applications and accepted 1,149 yielding a 13.7% acceptance rate. Amherst was ranked as the second best liberal arts college in the country by U.S. News & World Report, and 12th out of all U.S. colleges and universities by Forbes in their 2016 rankings. Amherst competes in the New England Small College Athletic Conference.Amherst has historically had close relationships and rivalries with Williams College and Wesleyan University which form the Little Three colleges. The college is a member of the Five College Consortium, which allows its students to attend classes at four other Pioneer Valley institutions. These include Mount Holyoke College, Smith College, Hampshire College, and the University of Massachusetts Amherst.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/endowment
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://dbpedia.org/datatype/usDollar
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V2.194E9
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/facultySize
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V285
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/motto
p71
ssg8
(dp72
Vtype
p73
Vliteral
p74
sVvalue
p75
VLet them enlighten the lands
p76
ssa(dp77
g7
(dp78
Vtype
p79
Vuri
p80
sVvalue
p81
Vhttp://dbpedia.org/ontology/motto
p82
ssg8
(dp83
Vtype
p84
Vliteral
p85
sVvalue
p86
VTerras Irradient (Latin)
p87
ssa(dp88
g7
(dp89
Vtype
p90
Vuri
p91
sVvalue
p92
Vhttp://dbpedia.org/ontology/numberOfUndergraduateStudents
p93
ssg8
(dp94
Vdatatype
p95
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p96
sVtype
p97
Vtyped-literal
p98
sVvalue
p99
V1795
p100
ssa(dp101
g7
(dp102
Vtype
p103
Vuri
p104
sVvalue
p105
Vhttp://dbpedia.org/ontology/officialSchoolColour
p106
ssg8
(dp107
Vtype
p108
Vliteral
p109
sVvalue
p110
VPurple and white
p111
ssa(dp112
g7
(dp113
Vtype
p114
Vuri
p115
sVvalue
p116
Vhttp://dbpedia.org/ontology/wikiPageExtracted
p117
ssg8
(dp118
Vdatatype
p119
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p120
sVtype
p121
Vtyped-literal
p122
sVvalue
p123
V2016-10-27T10:57:17Z
p124
ssa(dp125
g7
(dp126
Vtype
p127
Vuri
p128
sVvalue
p129
Vhttp://dbpedia.org/ontology/wikiPageLength
p130
ssg8
(dp131
Vdatatype
p132
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p133
sVtype
p134
Vtyped-literal
p135
sVvalue
p136
V53484
p137
ssa(dp138
g7
(dp139
Vtype
p140
Vuri
p141
sVvalue
p142
Vhttp://dbpedia.org/ontology/wikiPageModified
p143
ssg8
(dp144
Vdatatype
p145
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p146
sVtype
p147
Vtyped-literal
p148
sVvalue
p149
V2016-10-22T05:10:23Z
p150
ssa(dp151
g7
(dp152
Vtype
p153
Vuri
p154
sVvalue
p155
Vhttp://dbpedia.org/ontology/wikiPageOutDegree
p156
ssg8
(dp157
Vdatatype
p158
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p159
sVtype
p160
Vtyped-literal
p161
sVvalue
p162
V189
p163
ssasVordered
p164
I01
ss.