(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VLouisiana (/lu\u02d0\u02cci\u02d0zi\u02c8æn\u0259/ or /\u02cclu\u02d0zi\u02c8æn\u0259/; French: État de Louisiane, [lwizjan]; Louisiana Creole: Léta de la Lwizyàn) is a state located in the southern region of the United States. Louisiana is the 31st most extensive and the 25th most populous of the 50 United States. Its capital is Baton Rouge and largest city is New Orleans. Louisiana is the only state in the U.S. with political subdivisions termed parishes, which are the local government's equivalent to counties. The largest parish by population is East Baton Rouge Parish, and the largest by land area is Plaquemines. Louisiana is bordered by Arkansas to the north, Mississippi to the east, Texas to the west, and the Gulf of Mexico to the south.Much of the state's lands were formed from sediment washed down the Mississippi River, leaving enormous deltas and vast areas of coastal marsh and swamp. These contain a rich southern biota; typical examples include birds such as ibis and egrets. There are also many species of tree frogs, and fish such as sturgeon and paddlefish. In more elevated areas, fire is a natural process in the landscape, and has produced extensive areas of longleaf pine forest and wet savannas. These support an exceptionally large number of plant species, including many species of orchids and carnivorous plants.Some Louisiana urban environments have a multicultural, multilingual heritage, being so strongly influenced by a mixture of 18th-century French, Spanish, Native American, and African cultures that they are considered to be exceptional in the US. Before the American purchase of the territory in 1803, the current Louisiana State had been both a French colony and for a brief period, a Spanish one. In addition, colonists imported numerous African people as slaves in the 18th century. Many came from peoples of the same region of West Africa, thus concentrating their culture. In the post-Civil War environment, Anglo-Americans increased the pressure for Anglicization, and in 1921, English was made the only official language of the state. Louisiana has more Native American tribes than any other southern state, including four that are federally recognized, ten that are state recognized, and four that have not yet received recognition.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VLouisiana (/lu\u02d0\u02cci\u02d0zi\u02c8æn\u0259/ or /\u02cclu\u02d0zi\u02c8æn\u0259/; French: État de Louisiane, [lwizjan]; Louisiana Creole: Léta de la Lwizyàn) is a state located in the southern region of the United States. Louisiana is the 31st most extensive and the 25th most populous of the 50 United States. Its capital is Baton Rouge and largest city is New Orleans. Louisiana is the only state in the U.S. with political subdivisions termed parishes, which are the local government's equivalent to counties. The largest parish by population is East Baton Rouge Parish, and the largest by land area is Plaquemines. Louisiana is bordered by Arkansas to the north, Mississippi to the east, Texas to the west, and the Gulf of Mexico to the south.Much of the state's lands were formed from sediment washed down the Mississippi River, leaving enormous deltas and vast areas of coastal marsh and swamp. These contain a rich southern biota; typical examples include birds such as ibis and egrets. There are also many species of tree frogs, and fish such as sturgeon and paddlefish. In more elevated areas, fire is a natural process in the landscape, and has produced extensive areas of longleaf pine forest and wet savannas. These support an exceptionally large number of plant species, including many species of orchids and carnivorous plants. Louisiana has more Native American tribes than any other southern state, including four that are federally recognized, ten that are state recognized, and four that have not yet received recognition.Some Louisiana urban environments have a multicultural, multilingual heritage, being so strongly influenced by a mixture of 18th-century French, Spanish, Native American, and African cultures that they are considered to be exceptional in the US. Before the American purchase of the territory in 1803, the current Louisiana State had been both a French colony and for a brief period, a Spanish one. In addition, colonists imported numerous African people as slaves in the 18th century. Many came from peoples of the same region of West Africa, thus concentrating their culture. In the post-Civil War environment, Anglo-Americans increased the pressure for Anglicization, and in 1921, English was for a time made the sole language of instruction in Louisiana schools before a policy of multilingualism was revived in 1974. There has never been an official language in Louisiana, and the state constitution enumerates "the right of the people to preserve, foster, and promote their respective historic, linguistic, and cultural origins," whether English, French, Spanish, or otherwise.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/wikiPageExtracted
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V2016-11-02T14:15:09Z
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/wikiPageLength
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V145286
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/wikiPageModified
p71
ssg8
(dp72
Vdatatype
p73
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p74
sVtype
p75
Vtyped-literal
p76
sVvalue
p77
V2016-11-01T20:53:37Z
p78
ssa(dp79
g7
(dp80
Vtype
p81
Vuri
p82
sVvalue
p83
Vhttp://dbpedia.org/ontology/wikiPageOutDegree
p84
ssg8
(dp85
Vdatatype
p86
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p87
sVtype
p88
Vtyped-literal
p89
sVvalue
p90
V718
p91
ssasVordered
p92
I01
ss.