(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VThe Florida Keys are a coral cay archipelago located off the southern coast of Florida, forming the southernmost portion of the continental United States. They begin at the southeastern coast of the Florida peninsula, about 15 miles (24 km) south of Miami, and extend in a gentle arc south-southwest and then westward to Key West, the westernmost of the inhabited islands, and on to the uninhabited Dry Tortugas. The islands lie along the Florida Straits, dividing the Atlantic Ocean to the east from the Gulf of Mexico to the northwest, and defining one edge of Florida Bay. At the nearest point, the southern part of Key West is just 90 miles (140 km) from Cuba. The Florida Keys are between about 23.5 and 25.5 degrees North latitude.The climate of the Keys is defined as tropical savanna according to Köppen climate classification. More than 95 percent of the land area lies in Monroe County, but a small portion extends northeast into Miami-Dade County, such as Totten Key. The total land area is 137.3 square miles (356 km2). As of the 2010 census the population was 73,090 with an average density of 532.34 per square mile (205.54/km2), although much of the population is concentrated in a few areas of much higher density, such as the city of Key West, which has 32% of the entire population of the Keys. The US Census population estimate for 2014 is 77,136.The city of Key West is the county seat of Monroe County. The county consists of a section on the mainland which is almost entirely in Everglades National Park, and the Keys islands from Key Largo to the Dry Tortugas.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/wikiPageExtracted
p32
ssg8
(dp33
Vdatatype
p34
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p35
sVtype
p36
Vtyped-literal
p37
sVvalue
p38
V2016-10-30T13:21:45Z
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/wikiPageLength
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V28718
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/wikiPageModified
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#dateTime
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V2016-10-19T18:54:02Z
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/wikiPageOutDegree
p71
ssg8
(dp72
Vdatatype
p73
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p74
sVtype
p75
Vtyped-literal
p76
sVvalue
p77
V241
p78
ssasVordered
p79
I01
ss.