(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VGlentel is a Canadian retail firm. Based in Burnaby, the company deals primarily as a retailer of mobile phone services; in Canada, the company operates over 400 wireless outlets operating under the Tbooth Wireless and WirelessWave brands, particularly in mall kiosks. Glentel outlets sell services from Bell Mobility and Rogers Wireless\u2014who jointly own the company, along with their respective pre-paid/value brands (such as Fido and Virgin Mobile), and SaskTel in Saskatchewan. The company also operates store-within-a-store kiosks at Canadian Costco locations under the Wireless etc. brand, and operated as Target Mobile at Target locations in Canada until the chain's closure. In 2010, the company first expanded into the United States with its acquisition of Verizon Wireless retail chain Diamond Wireless. On November 28, 2014, BCE Inc. announced that it would acquire Glentel for $670 million, pending regulatory approval, in an effort to boost its retail presence. After a dispute with Rogers, who argued that it was contractually required to consent to any change in ownership of the company, Bell announced that it would divest a 50% stake in Glentel to Rogers upon the closure of the acquisition, turning the company into a 50/50 joint venture between the rival firms.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/foundingYear
p32
ssg8
(dp33
Vdatatype
p34
Vhttp://www.w3.org/2001/XMLSchema#gYear
p35
sVtype
p36
Vtyped-literal
p37
sVvalue
p38
V1963
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/netIncome
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://dbpedia.org/datatype/usDollar
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V1.59E7
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/numberOfEmployees
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V2100
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/numberOfLocations
p71
ssg8
(dp72
Vdatatype
p73
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p74
sVtype
p75
Vtyped-literal
p76
sVvalue
p77
V400
p78
ssa(dp79
g7
(dp80
Vtype
p81
Vuri
p82
sVvalue
p83
Vhttp://dbpedia.org/ontology/operatingIncome
p84
ssg8
(dp85
Vdatatype
p86
Vhttp://dbpedia.org/datatype/usDollar
p87
sVtype
p88
Vtyped-literal
p89
sVvalue
p90
V2.45E7
p91
ssa(dp92
g7
(dp93
Vtype
p94
Vuri
p95
sVvalue
p96
Vhttp://dbpedia.org/ontology/revenue
p97
ssg8
(dp98
Vdatatype
p99
Vhttp://dbpedia.org/datatype/usDollar
p100
sVtype
p101
Vtyped-literal
p102
sVvalue
p103
V3.08E8
p104
ssasVordered
p105
I01
ss.