(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ves
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VLa sierra de Agua Dulce es un cordal montañoso en centro-norte del desierto de Sonora al suroeste de Arizona, en Estados Unidos de América. La sierra está ubicada en el extremo suroeste del condado de Pima, justo al norte del frontera internacional entre México y Estados Unidos, a unas 30 millas de Ajo. Posee unas 15 millas de longitud en su cordal principal y cerca de 5 millas de ancho. La sierra se encuentra dentro del refugio de vida silvestre de Cabeza Prieta. La cima máxima de la sierra se encuentra a 869 msnm en las coordenadas 32°01'32"N, 113°08'44"W (NAD 1983 datum). Se le ha denominado "sierra de Agua Dulce" durante los últimos 100 años, con anterioridad fue llamada "Sierra del Ojo" y "Sierra de Sonoita" en mapas más antiguos.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VThe Agua Dulce Mountains are a mountain range in the north-central Sonoran Desert of southwestern Arizona. The range is located in the extreme southwestern portion of Pima County, Arizona, immediately north of the international boundary with Mexico and about 30 miles southwest of Ajo, Arizona. The range has three main sections that total about 15 miles in length and about nine miles in width. The range is located entirely within the Cabeza Prieta National Wildlife Refuge. The highpoint of the range is 2,852 feet (869 meters) above sea level and is located at 32°01'32"N, 113°08'44"W (NAD 1983 datum). The summit is unnamed, but is marked on U.S. Geological Survey (USGS) maps for the "Quitovaquita" benchmark that was placed on the summit in 1920. The original surveyed height was 2,850 feet above sea level, but recent datum adjustments calculate the summit to be two feet higher. The name of the range has been in use for at least 100 years, though it has been called the "Sierra del Ojo" and the "Sonoyta Mountains" on some older maps. A map created by the U.S. Army Corps of Engineers around 1920 labeled the range the "Quitovaquita Mountains." This is in reference to Quitobaquito Springs, which lie approximately nine miles southeast of the range in what are now called the Quitobaquito Hills. The Quitobaquito Hills, however, do not share a connection with the Agua Dulce Mountains. "Agua Dulce" means "sweet water" in Spanish and refers to pools of non-saline water on the Sonoyta River several miles to the south in Mexico. These pools are in contrast to "Agua Salada," which is located further downstream on the river and yields only highly mineralized and brackish water. The range also contains a small spring on its southern slope that also bears the name Agua Dulce, though it is likely that the range is named for the pools on the river rather than the spring, since the pools played prominently in the history of the area whereas the spring is small and well away from the historical Sonoyta River travel corridor. The range is home to a number of abandoned mines, most notably the Papago Mine and the Legal Tender Mine, which were worked in the late 19th and early 20th centuries. Papago Well was drilled nearby during the same period to provide water to the mines. Later the well was used to provide water to cattle that grazed in the area, and now the windmill pumps water to a guzzler for wildlife. The Davidson Canyon area and the associated bajada to the south of the range contain the northernmost populations of senita cactus (Pachycereus schottii). This columnar cactus is very common further south in Mexico, but in the United States it is restricted to small areas of Organ Pipe Cactus National Monument and this isolated population in the Cabeza Prieta National Wildlife Refuge.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/elevation
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#double
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V869.0
p52
ssasVordered
p53
I01
ss.