(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VThe Gran Turismo official steering wheels (such as the GT FORCE or Driving Force, see the trademark symbols difference) are a series of steering wheels designed by Logitech (a.k.a. Logicool in Japan) in collaboration with Polyphony Digital. These racing games controllers are designed to be used with the PlayStation 2 and PlayStation 3 systems but later models can be used on PC as well due to their USB connection.The GT Force is the central part of a driving simulation cockpit installation. Official kits are co-designed and released in Japan by Logicool and Sparco (distributed by import tuner Endless in North America), while compatible kits are designed and released worldwide by European manufacturers such as Playseat® and MoveTech.
p26
ssasVordered
p27
I01
ss.