(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Vde
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VPirotan (auch Pirothan, Gujarati: \u0aaa\u0abf\u0ab0\u0acb\u0aa4\u0aa8, Hindi: \u092a\u093f\u0930\u094b\u0924\u0928, Pirotan) ist eine Insel im Arabischen Meer und Teil des Marine National Park des Distrikts Jamnagar, Gujarat in Indien. Sie liegt etwa 12 km vor der Küste Indiens in Nähe der Hafenstadt Bedi. Die Nachbarinsel Rozi liegt etwa 10 km südöstlich. Die Insel gehört zu einem 42 Inseln umfassenden Schutzgebiet, zu dem Besucher nur mit seltenen Ausnahmegenehmigungen Zutritt bekommen.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ves
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VPirotan (en Guyarati: \u0aaa\u0abf\u0ab0\u0acb\u0aa4\u0aa8, en Hindi: \u092a\u093f\u0930\u094b\u0924\u0928) es una isla del Mar Arábigo en el Parque Nacional Marino distrito Jamnagar, del estado de Gujarat, en la India. Se encuentra a 12 millas náuticas (22 kilómetros) de la costa (de Puerto Bedi), consiste en manglares y playas de aguas bajas, y tiene una superficie de 3 kilómetros cuadrados. El centro de la isla está en las coordenadas 22°35\u203259.7\u2033N 69°57\u203220.8\u2033E\ufeff / \ufeff22.599917, 69.955778. La isla Rozi se encuentra a unos 10 kilómetros al sureste. De las 42 islas en el parque, Pirotan es la más popular y es una de las dos islas donde los visitantes normalmente tienen permitido estar. Las visitas está estrictamente limitadas, se necesita un permiso del Departamento Forestal, de Aduanas y Puertos. Los manglares son principalmente de las especies de Rhizophora, Avicennia y Ceriops.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/abstract
p45
ssg8
(dp46
Vxml:lang
p47
Ven
p48
sVtype
p49
Vliteral
p50
sVvalue
p51
VPirotan Island (also known as Pirothan) is an Arabian Sea island in the Marine National Park, Jamnagar District of Gujarat state, India. It is located 12 nautical miles (22 km) off the coast (Bedi Port), consists of mangroves and low-tide beaches, and has an area of 3 square kilometres. Rozi island is located about 10 kilometres to the southeast. Of the 42 islands in the park, Pirotan Island is the most popular and is one of the two islands where visitors are normally permitted. Visitation is strictly limited, permission is required from the Forest Department, Customs Department and the Ports. The mangroves consist mainly of species of Rhizophora, Avicennia and Ceriops.
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/buildingEndDate
p58
ssg8
(dp59
Vtype
p60
Vliteral
p61
sVvalue
p62
V1898 (first)
p63
ssa(dp64
g7
(dp65
Vtype
p66
Vuri
p67
sVvalue
p68
Vhttp://dbpedia.org/ontology/height
p69
ssg8
(dp70
Vdatatype
p71
Vhttp://www.w3.org/2001/XMLSchema#double
p72
sVtype
p73
Vtyped-literal
p74
sVvalue
p75
V18.3
p76
ssasVordered
p77
I01
ss.