(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/birthDate
p19
ssg8
(dp20
Vdatatype
p21
Vhttp://www.w3.org/2001/XMLSchema#date
p22
sVtype
p23
Vtyped-literal
p24
sVvalue
p25
V1940-1-1
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VCraig Powell (born 1940) in Wollongong, New South Wales, Australia is an Australian poet. For ten years, he lived in Canada before returning to his homeland. Powell graduated in medicine from Sydney University and later specialised in Psychiatry. From 1972 to 1982, he lived in Canada where he trained with the Toronto Institute of Psychoanalysis. He now lives in Sydney, Australia where he is a psychoanalyst in private practice and a visiting medical officer in Mental Health, at the Prince of Wales Hospital. He won the 1983 Mattara Newcastle Poetry Prize and was a co-winner of the 45th International Poetry Competition (1989) organized by the Quarterly Review of Literature, Princeton, New Jersey. He has published eight poetry collections and individual poems were included in The Best Australian Poetry 2007 and in New Oxford Book of Australian Verse. More recently he published chapbooks The Poem As A Place (September 2004) and Poems For A Marriage (July 2008) through Picaro Press.
p39
ssasVordered
p40
I01
ss.