(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/MeanOfTransportation/length
p19
ssg8
(dp20
Vdatatype
p21
Vhttp://dbpedia.org/datatype/millimetre
p22
sVtype
p23
Vtyped-literal
p24
sVvalue
p25
V81000.0
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ves
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VLa clase João Coutinho es una serie de seis corbetas construidas para la Marina Portuguesa para prestar servicios en las colonias portuguesas en África. Las corbetas, fueron diseñadas en Portugal, por el ingeniero Rogério d'Oliveira, pero la urgente necesidad de su entrada en servicio, debido a las guerras coloniales, hicieron necesario el que se contratara su construcción a astilleros situados en el exterior. De los seis buques construidos, los tres primeros lo fueron en los astilleros alemanes de Blohm + Voss, y los tres restantes fueron construidos por la Empresa Nacional Bazán en España. Todos fueron botados entre 1970 y 1971. Desde 1970 hasta el final del conflicto en 1975, las corbetas fueron usadas en tareas de patrulla y en misiones de apoyo artillero en Angola, Mozambique, Guinea-Bissau y Cabo Verde. Tras la independencia de las colonias, las corbetas, fueron asignadas a tareas de patrulla en aguas territoriales portuguesas y de control de la Zona Económica Exclusiva. La clase João Coutinho ha servido como base para otros diseños de corbetas como pueden ser las clases: \u000a*  Baptista de Andrade (Portugal).  \u000a*  Descubierta (España, Egipto y Marruecos). \u000a*  Espora (MEKO 140) (Argentina) \u000a*  D'Estienne d'Orves (A-69) (Francia, Argentina y Turquía)
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/abstract
p45
ssg8
(dp46
Vxml:lang
p47
Vde
p48
sVtype
p49
Vliteral
p50
sVvalue
p51
VDie João-Coutinho-Klasse ist eine Schiffsklasse von sechs Korvetten der portugiesischen Marine. Sie stehen seit Mitte der 1970er-Jahre im Dienst. Die noch in Dienst stehenden Einheiten werden heute als Patrouillenboote eingesetzt. Aus der Klasse wurden einige weitere Korvettenklassen abgeleitet. Hierzu zählten die Baptista-de-Andrade-, Descubierta-, Espora-bzw. MEKO 140- und D'Estienne-d'Orves-Klasse.
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/abstract
p58
ssg8
(dp59
Vxml:lang
p60
Vit
p61
sVtype
p62
Vliteral
p63
sVvalue
p64
VLa classe João Coutinho è un tipo di corvette di scorta oceanica in servizio nella marina militare portoghese. Queste navi furono progettate per operare nelle acque dei territori di oltremare portoghesi e vista la necessità dei portoghesi di averle presto a disposizione in conseguenza della guerra coloniale in cui i portoghesi erano impegnati, si dovette ricorrere per la loro costruzione ai cantieri tedeschi e spagnoli e queste navi furono messe in servizio tra il 1970 e il 1971. Dal 1970 al 1975, queste navi furono utilizzate per la funzione per la quale erano state progettate, impegnate in missioni di appoggio nelle acque dell'Angola, della Guinea portoghese, Mozambico e Capo Verde. Con l'indipendenza dei territori di oltremare queste corvette vennero utilizzate per missioni di vigilanza, ricerca in mare e missioni di salvataggio nelle acque territoriali portoghesi. Data la validità del progetto alla Classe João Coutinho si sono ispirate varie altre classi di corvette di altre marine, quali le portoghesi Baptista de Andrade successive alle João Coutinho, le spagnole Descubierta in servizio anche nelle marine del Marocco e dell'Egitto e le argentine Espora.
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/abstract
p71
ssg8
(dp72
Vxml:lang
p73
Vja
p74
sVtype
p75
Vliteral
p76
sVvalue
p77
V\u30b8\u30e7\u30a2\u30f3\u30fb\u30b3\u30fc\u30c1\u30cb\u30e7\u7d1a\u30b3\u30eb\u30d9\u30c3\u30c8\uff08\u30dd\u30eb\u30c8\u30ac\u30eb\u8a9e: Corveta classe João Coutinho\uff09\u306f\u3001\u30dd\u30eb\u30c8\u30ac\u30eb\u6d77\u8ecd\u306e\u30b3\u30eb\u30d9\u30c3\u30c8\u306e\u8266\u7d1a\u3002\u30b8\u30a7\u30fc\u30f3\u6d77\u8ecd\u5e74\u9451\u3084\u30a2\u30e1\u30ea\u30ab\u6d77\u8ecd\u5354\u4f1a\uff08USNI\uff09\u3067\u306f\u3001\u30da\u30ca\u30f3\u30c8\u30fb\u30ca\u30f3\u30d0\u30fc\u306b\u6e96\u3058\u3066\u30d5\u30ea\u30b2\u30fc\u30c8\u3068\u3057\u3066\u7a2e\u5225\u3057\u3066\u3044\u308b\u3002
p78
ssa(dp79
g7
(dp80
Vtype
p81
Vuri
p82
sVvalue
p83
Vhttp://dbpedia.org/ontology/abstract
p84
ssg8
(dp85
Vxml:lang
p86
Vpt
p87
sVtype
p88
Vliteral
p89
sVvalue
p90
VA Classe João Coutinho é um tipo de escoltador oceânico ao serviço da Marinha Portuguesa. Esta classe foi projectada pelo engenheiro português Rogério d'Oliveira como um tipo de navio especialmente adaptado à atuação nas águas dos territórios ultramarinos portugueses, garantindo aí uma presença naval em defesa da soberania de Portugal. Para poderem ser construídos em alguma quantidade de modo a estarem presentes em todos estes territórios, era necessário que os navios fossem económicos e fáceis de manter. Estes navios seriam a versão moderna das canhoneiras do século XIX e dos avisos coloniais de 2ª classe da década de 1930. A Marinha Portuguesa classificou os navios da nova classe como corvetas, apesar da sua dimensão já os inserir na categoria das fragatas ligeiras e de terem recebido o prefixo F no seu número de amura. Pela urgência da Marinha Portuguesa em ter os navios ao serviço, em virtude da Guerra do Ultramar, recorreu-se a estaleiros alemães e espanhóis para a construção da classe, sendo os navios lançados à água em 1970 e 1971. De 1970 até 1975, os navios foram utilizados na função principal para a qual tinham sido projectados, atuando em missões de soberania e apoio de fogo nas águas de Angola, Guiné Portuguesa, Moçambique e Cabo Verde. Com a independência dos territórios ultramarinos, as corvetas passaram a ser utilizadas sobretudo em missões de vigilância, fiscalização, busca e salvamento nas águas de Portugal. Dada a excepcional qualidade do projeto, a Classe João Coutinho deu origem a várias outras classes de navios, utilizados por várias marinhas: Classe Baptista de Andrade (Portugal), Classe Descubierta (Espanha, Egipto e Marrocos), Classe Espora (MEKO 140) (Argentina) e Classe D'Estienne d'Orves (A-69) (França, Argentina e Turquia).
p91
ssa(dp92
g7
(dp93
Vtype
p94
Vuri
p95
sVvalue
p96
Vhttp://dbpedia.org/ontology/abstract
p97
ssg8
(dp98
Vxml:lang
p99
Vpl
p100
sVtype
p101
Vliteral
p102
sVvalue
p103
VKorwety typu João Coutinho \u2013 typ sze\u015bciu portugalskich korwet, zbudowanych na pocz\u0105tku lat 70. XX wieku dla Portugalskiej Marynarki Wojennej. Trzy okr\u0119ty zbudowane zosta\u0142y przez hiszpa\u0144sk\u0105 stoczni\u0119 BAZAN, a pozosta\u0142e trzy przez niemieckie przedsi\u0119biorstwo Blohm + Voss. Okr\u0119ty zaprojektowano z my\u015bl\u0105 o s\u0142u\u017cbie w koloniach portugalskich \u2013 Angoli, Mozambiku, Wyspach Zielonego Przyl\u0105dka oraz Gwinei Bissau. Podczas trwaj\u0105cych na ich obszarze do 1975 roku wojen kolonialnych korwety pe\u0142ni\u0142y funkcje patrolowe i wsparcia ogniowego. Po uzyskaniu niepodleg\u0142o\u015bci przez kolonie, okr\u0119ty zacz\u0119\u0142y pe\u0142ni\u0107 s\u0142u\u017cb\u0119 na portugalskich wodach terytorialnych. Na podstawie okr\u0119tów typu João Coutinho powsta\u0142y cztery zmodyfikowane korwety typu Baptista de Andrade.
p104
ssa(dp105
g7
(dp106
Vtype
p107
Vuri
p108
sVvalue
p109
Vhttp://dbpedia.org/ontology/abstract
p110
ssg8
(dp111
Vxml:lang
p112
Ven
p113
sVtype
p114
Vliteral
p115
sVvalue
p116
VThe João Coutinho-class corvettes were a series of corvettes built for the Portuguese Navy for service in Portugal's African colonies. The corvettes were designed in Portugal by naval engineer Rogério de Oliveira, but the urgent need of their services in the Portuguese Colonial War meant that the construction of the ships was assigned to foreign shipyards. Six ships were built; the first three ships were built by Blohm + Voss and the remaining three by Empresa Nacional Bazán. The ships were launched in 1970 and 1971. From 1970 until the end of the conflict in 1975, the corvettes were used for patrol and fire-support missions in Angola, Mozambique, Guinea and Cape Verde. After the African colonies gained their independence, the corvettes were assigned to patrol duties in Portuguese territorial waters. The João Coutinho class served as the basis for several other designs: Baptista de Andrade-class corvettes (Portugal), Descubierta-class corvettes (Spain, Egypt and Morocco), Espora-class (MEKO 140) corvettes (Argentina) and D'Estienne d'Orves-class (A-69) avisos (France, Argentina and Turkey) . The ships were finally decommissioned in 2015.
p117
ssa(dp118
g7
(dp119
Vtype
p120
Vuri
p121
sVvalue
p122
Vhttp://dbpedia.org/ontology/length
p123
ssg8
(dp124
Vdatatype
p125
Vhttp://www.w3.org/2001/XMLSchema#double
p126
sVtype
p127
Vtyped-literal
p128
sVvalue
p129
V81.0
p130
ssa(dp131
g7
(dp132
Vtype
p133
Vuri
p134
sVvalue
p135
Vhttp://dbpedia.org/ontology/shipBeam
p136
ssg8
(dp137
Vdatatype
p138
Vhttp://www.w3.org/2001/XMLSchema#double
p139
sVtype
p140
Vtyped-literal
p141
sVvalue
p142
V10.3
p143
ssasVordered
p144
I01
ss.