(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ves
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VSELTHER es una compañía transnacional mexicana productora de colchones y sistemas de descanso. Actualmente es una de las líderes en México y América Latina en la producción de colchones. SELTHER nace en 1970 con una unidad productiva ubicada en el DF. En el transcurso de los años '80 abre plantas de producción en Monterrey NL, Guadalajara JAL y en el Estado de México. Desde el 2001 forma parte de Grupo GARD, basado en Monterrey, NL y con intereses en diferentes sectores de la rama inmobiliaria, industrial y de alta tecnología. En 1995 inicia sus exportaciones a Estados Unidos y Centroamérica, inaugurando una nueva planta en Costa Rica en 2006.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VSELTHER is a transnational Mexican company active in the mattress and bedding industry. At present Selther is one of the leaders in Mexico and Latin America in the mattress industry. SELTHER was established in Mexico City in 1970 with a small production unit. Through the 1980s Selther opened new production plants in Monterrey NL, Guadalajara JAL and the State of Mexico. Since 2001 Selther is part of GARD Group. Based in Monterrey, NL GARD Group is active in some industries such as real estate, industrial manufacturing and RFID technology development. In 1995 Selther began exporting to the US and to Central America. In July 2006 Selther opened a new plant in Costa Rica to attend the Central and South American markets while in 2007 it opened a plant in Mexicali and started operations in Europe. Starting 2009, Selther has entered a strong downsizing process mainly due to the current economic situation which has led to cut off 40% of the labour force and the shut down of the Mexicali plant and the Madrid offices.. As of September 2009, Jose Benavides Luna has been appointed as the new CEO.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/foundingYear
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#gYear
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V1970
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/numberOfEmployees
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V600
p65
ssasVordered
p66
I01
ss.