(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ves
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VEl valle de Nuria (en catalán: la vall de Núria) es un valle pirenaico situado en el término municipal de Queralbs, en la provincia catalana de Gerona (España). Situado a una altitud de 2.000 metros sobre el nivel del mar, este valle es accesible por medio de un ferrocarril de cremallera (Cremallera de Nuria, FGC) o bien siguiendo alguna de los caminos de montaña que llegan a Nuria. En el valle se encuentra ubicado el Santuario de la Virgen de Nuria en el que se redactó en 1931 el primer estatuto de autonomía de Cataluña.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Vde
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VDas Pyrenäental Vall de Núria (\u201aTal von Núria\u2018), nahe der Grenze zu Frankreich in der Comarca Ripollès im Norden Kataloniens gelegen, ist ein bedeutender religiöser Ort und ein beliebtes Ausflugsziel, das vielfältige Ski- und Wandermöglichkeiten bietet. Da das Gebirgstal autofrei ist, fährt eine Zahnradbahn (die Cremallera de Núria) vom Talort Ribes de Freser über Queralbs in das Tal; an der Bergstation befinden sich auf 1.967 Metern das Santuari de la Mare de Déu de Núria, das Sanktuarium (Heiligtum) der Muttergottes von Núria, die Einsiedlerkapelle Sant Gil, ein Hotel, ein kleines Wasserkraftwerk und einige Liftanlagen. Vor dem Heiligtum befindet sich ein Stausee, der im Winter das Wasser für die Beschneiungsanlagen liefert. Oberhalb des Stausees befindet sich eine Jugendherberge. Das Vall de Núria ist Ausgangspunkt für Wanderungen zu mehreren knappen Dreitausendern in den Pyrenäen.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/abstract
p45
ssg8
(dp46
Vxml:lang
p47
Vfr
p48
sVtype
p49
Vliteral
p50
sVvalue
p51
VLa vallée de Núria (en catalan vall de Núria) est une vallée pyrénéenne située dans la municipalité de Queralbs, dans la province de Gérone, dans la communauté autonome de Catalogne (Espagne). Située à une altitude de 2 000 mètres, on accède à cette vallée par un train à crémaillère, ou par quelques sentiers de montagne qui montent à Núria. Dans la vallée se trouve le sanctuaire de la Vierge de Núria, où le premier statut d'autonomie de la Catalogne fut rédigé en 1931.
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/abstract
p58
ssg8
(dp59
Vxml:lang
p60
Ven
p61
sVtype
p62
Vliteral
p63
sVvalue
p64
VLa Vall de Núria (Catalan pronunciation: [\u026b\u0259 \u02c8\u03b2a\u028e d\u0259 \u02c8nu\u027ei\u0259], "The Valley of Núria") is a south-opening valley coming down from the crest of the Pyrenees within the municipality of Queralbs, province of Girona, community of Catalonia, Spain. The floor of the valley lies about 2,000 metres (6,600 ft) above sea level and is accessible from the south via a rack railway (the Vall de Núria Rack Railway) or by foot, and from France to the north by footpaths. There are no roads to access the valley. The place is historically notable for the 1931 drafting of the first Catalan Statute of Autonomy, in the Sanctuary of the Virgin of Núria.
p65
ssasVordered
p66
I01
ss.