(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/Infrastructure/length
p19
ssg8
(dp20
Vdatatype
p21
Vhttp://dbpedia.org/datatype/kilometre
p22
sVtype
p23
Vtyped-literal
p24
sVvalue
p25
V0.535
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VThe Dahla Dam is the largest dam in Kandahar Province, and the second largest in Afghanistan. It was built in 1952. Over the years during the wars due to neglect the project was subject to siltation of the reservoir, the canal system and other appurtenant works which reduced its irrigation benefits. This necessitated undertaking rehabilitation of the project which was envisaged in two phases with the first phase involving desiltation works and pertinent components of the project to improve the water delivery system; this component was completed during March 2012 with full assistance provided by the Government of Canada. The second phase involves raising the height of the dam and the relevant dykes to compensate for the loss of storage in the dam due to siltation, and to achieve the full benefits of irrigation for which the dam was originally built. This component is now under implementation with financial and technical support from the US government
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/height
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#double
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V55.0
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/length
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#double
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V535.0
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/openingYear
p71
ssg8
(dp72
Vdatatype
p73
Vhttp://www.w3.org/2001/XMLSchema#gYear
p74
sVtype
p75
Vtyped-literal
p76
sVvalue
p77
V1952
p78
ssasVordered
p79
I01
ss.