(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Vde
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VUnter Baby Talk oder Motherese (Aussprache: [\u02c8m\u028cð\u0259\u0279i\u02d0s]; engl.), ungenau auch Ammensprache, Kinder- oder Babysprache oder umgangssprachlich \u201eMutterisch\u201c oder \u201eElterisch\u201c genannt, versteht man eine Varietät einer Sprache, die bevorzugt gegenüber Säuglingen und Kleinkindern gebraucht wird. Baby Talk gilt als etablierter Begriff der Kindersprachenforschung für ein kulturübergreifendes Phänomen als eine Form universalen Sprechhandelns. Daraus abgeleitet wurde der Ausdruck secondary baby talk für den Sprachgebrauch, der insbesondere von Pflegepersonal gegenüber älteren und pflegebedürftigen Menschen angewendet wird.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VBaby talk, also referred to as caretaker speech, infant-directed speech (IDS), child-directed speech (CDS) or motherese, is usually delivered with a "cooing" pattern of intonation different from that of normal adult speech: high in pitch, with many glissando variations that are more pronounced than those of normal speech. It frequently displays hyperarticulation, which is an increase in the distances between peripheral vowels (such as [i], [u], and [a]). Baby talk is also characterized by the shortening and simplifying of words. Baby talk is similar to what is used by people when talking to their pets (pet-directed speech). When adults talk to each other using baby talk it is generally to either show affection by emulating the fondness shown by adults for children, or as a form of bullying or condescension as children are much less cognitively developed than adults, implying that the adult receiving the baby talk is less intelligent than the adult talking to them.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/abstract
p45
ssg8
(dp46
Vxml:lang
p47
Ves
p48
sVtype
p49
Vliteral
p50
sVvalue
p51
VEl baby talk (o en inglés, motherese) es el nombre que se usa para designar un subcódigo lingüístico que emplean los adultos y los niños mayores de 5-6 años, de forma espontánea, cuando se dirigen y comunican con niños más pequeños.
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/abstract
p58
ssg8
(dp59
Vxml:lang
p60
Vit
p61
sVtype
p62
Vliteral
p63
sVvalue
p64
VIl termine baby talk (detto anche motherese in inglese, reso in italiano con maternese o madrese) indica la varietà linguistica usata dagli adulti nel rivolgersi ai bambini piccoli.
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/abstract
p71
ssg8
(dp72
Vxml:lang
p73
Vja
p74
sVtype
p75
Vliteral
p76
sVvalue
p77
V\u5e7c\u5150\u8a9e\uff08\u3088\u3046\u3058\u3054\uff09\u3068\u306f\u3001\u4e73\u5e7c\u5150\u671f\u306e\u4f1a\u8a71\u306b\u7528\u3044\u3089\u308c\u308b\u8a00\u8449\u3002
p78
ssa(dp79
g7
(dp80
Vtype
p81
Vuri
p82
sVvalue
p83
Vhttp://dbpedia.org/ontology/abstract
p84
ssg8
(dp85
Vxml:lang
p86
Vfr
p87
sVtype
p88
Vliteral
p89
sVvalue
p90
VLe mamanais désigne la manière qu'ont les parents de s'adresser à leur nourrisson. Elle se caractérise par l'usage d'une voix inhabituellement haute et par la répétition des sonorités incluant l'augmentation des diphtongues. Le mamanais est parfois caractérisé comme un mode d'échange possédant une certaine musicalité. Globalement le débit du parent émetteur est ralenti et sa prosodie est inhabituelle. En général, le bébé répond par des sons « euh » successifs. Le mamanais est observable dans presque toutes les cultures.
p91
ssa(dp92
g7
(dp93
Vtype
p94
Vuri
p95
sVvalue
p96
Vhttp://dbpedia.org/ontology/abstract
p97
ssg8
(dp98
Vxml:lang
p99
Vpl
p100
sVtype
p101
Vliteral
p102
sVvalue
p103
VMowa matczyna (ang. motherese) \u2013 specjalna forma mowy o przesadnej intonacji, której doro\u015bli w niektórych kulturach u\u017cywaj\u0105 mówi\u0105c do niemowl\u0105t i ma\u0142ych dzieci. Mowa matczyna nazywana jest te\u017c cz\u0119sto mow\u0105 nianiek. Poj\u0119cie zosta\u0142o wprowadzone przez Anne Fernald. Zapoznaj si\u0119 z zastrze\u017ceniami dotycz\u0105cymi poj\u0119\u0107 medycznych i pokrewnych w Wikipedii.
p104
ssa(dp105
g7
(dp106
Vtype
p107
Vuri
p108
sVvalue
p109
Vhttp://dbpedia.org/ontology/abstract
p110
ssg8
(dp111
Vxml:lang
p112
Vpt
p113
sVtype
p114
Vliteral
p115
sVvalue
p116
VA expressão fala de bebê se refere ao modo de falar mais alto e cantado que os pais de um bebê geralmente adotam para se comunicar com ele, e que pode de acordo com alguns estudos ter origens biológicas.
p117
ssasVordered
p118
I01
ss.