(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/deathDate
p19
ssg8
(dp20
Vdatatype
p21
Vhttp://www.w3.org/2001/XMLSchema#date
p22
sVtype
p23
Vtyped-literal
p24
sVvalue
p25
V1532-0-0
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ves
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VGuamá fue un cacique taíno de la isla de Cuba que luchó contra la colonización española entre 1522 y 1532 en pleno apogeo del dominio español. Basado en las experiencias de Hatuey pudo sostenerse luchando durante casi diez años en las montañas del oriente cubano manteniendo en jaque a los colonizadores. Su rango de acción llegó a extenderse hasta la actual provincia de Camagüey. Guamá fue asesinado en 1532 por su hermano Olguama, mientras dormía. Guamá había raptado a la mujer de su hermano y ello fue la causa del asalto y posterior muerte ocasionada por un golpe contundente en la cabeza.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/abstract
p45
ssg8
(dp46
Vxml:lang
p47
Ven
p48
sVtype
p49
Vliteral
p50
sVvalue
p51
VGuamá (died c. 1532) was a Taíno rebel chief who led a rebellion against Spanish rule in Cuba in the 1530s. Legend states that Guamá was first warned about the Spanish conquistador by Hatuey, a Taíno cacique from what is now Haiti.
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/abstract
p58
ssg8
(dp59
Vxml:lang
p60
Vfr
p61
sVtype
p62
Vliteral
p63
sVvalue
p64
VGuamá (mort en 1532) était un chef rebelle du peuple des indiens Taïnos ayant conduit la rébellion contre la colonisation espagnole à Cuba dans les années 1530. Après la mort du gouverneur espagnol, Diego de Velázquez  (1460-1524), les répressions indigènes se sont intensifiées. En 1530, Guamá avait, sous son commandement, cinquante guerriers et continuait à recruter chez les yndios. La rébellion a eu principalement lieu dans les vastes forêts de Çagua, proche de Baracoa dans l'est de Cuba, mais également dans le sud et l'ouest de la Sierra Maestra. Guamá a été trahi et assassiné par son frère Oliguama en 1532.
p65
ssasVordered
p66
I01
ss.