(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VThe Biggest Loser (season 4) is the fourth season of the NBC reality television series entitled The Biggest Loser. The fourth season premiered on September 11, 2007 with 18 overweight contestants in a weight loss competition for an ultimate prize of $250,000. The Biggest Loser campus was located at California State University Channel Islands in Camarillo, California. The season four contestants were divided into 3 teams: the Red team, led by trainer Kim Lyons; the Blue team, led by trainer Bob Harper; and the Black team, led by trainer Jillian Michaels. The teams were formed on the first episode, with the Red and Blue teams being selected by the two players who had won a foot race across the desert. The Black team was formed with the 6 remaining contestants who were not selected for the Red and Blue teams. While the Red and Blue teams returned to the Biggest Loser campus, the Black team was left behind, believing that they had been eliminated already. Instead, they remained in the desert and trained in secret with their trainer, Jillian, until they arrived on campus for the weigh-in at the end of week 2.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/firstAirDate
p32
ssg8
(dp33
Vdatatype
p34
Vhttp://www.w3.org/2001/XMLSchema#date
p35
sVtype
p36
Vtyped-literal
p37
sVvalue
p38
V2007-09-11
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/numberOfEpisodes
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V15
p52
ssasVordered
p53
I01
ss.