(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VThe Family Research Institute (FRI), originally known as the Institute for the Scientific Investigation of Sexuality (ISIS), is an American non-profit organization based in Colorado Springs, Colorado which states that it has "...one overriding mission: to generate empirical research on issues that threaten the traditional family, particularly homosexuality, AIDS, sexual social policy, and drug abuse". The FRI is part of a movement of organizations, often faith-based (sometimes called the Christian right), which seek to influence the political debate in the United States. They seek "...to restore a world where marriage is upheld and honored, where children are nurtured and protected, and where homosexuality is not taught and accepted, but instead is discouraged and rejected at every level." The Boston Globe reported that the FRI's 2005 budget was less than $200,000. The FRI is run by Paul Cameron, who earned a doctorate in psychology at the University of Colorado at Boulder in 1966. Cameron founded the Institute for the Scientific Investigation of Sexuality in 1982, and this institute later became the FRI. The Family Research Institute is designated an anti-gay hate group by the Southern Poverty Law Center because of Cameron's discredited research and claims about LGBT people.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Vde
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VDas Family Research Institute (FRI), früher bekannt als Institute for the Scientific Investigation of Sexuality (ISIS), ist eine US-amerikanische evangelikal religiöse Organisation. Sie ist eine Non-Profit-Organisation mit Sitz in Colorado Springs, Colorado.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/foundingYear
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#gYear
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V1982
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/revenue
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://dbpedia.org/datatype/usDollar
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V70629.0
p65
ssasVordered
p66
I01
ss.