(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VSoto Cano Air Base (commonly known as Palmerola Air Base) is a Honduran military base 5 mi (8.0 km) to the south of Comayagua in Honduras. It houses between 500-600 US troops and is also used by the Honduran Air Force academy. The airbase became operational in 1981, changing the old location of the Honduras Air Force Academy in Toncontin, Tegucigalpa to Palmerola. The US government once used Palmerola as a base of operations to support its foreign policy objectives in the 1980s. Now the US military uses Soto Cano as a launching point for counter-narcotics missions in Central America as well as humanitarian aid missions throughout Honduras and Central America. In addition to the Honduran Air Force Academy, the US military's Joint Task Force Bravo (JTF-B) is headquartered at Soto Cano. JTF-B consists of four groups: MEDEL (Medical Element) a Military Hospital, ARFOR (Army Forces), JSF (Joint Security Forces), and the 1st Battalion-228th Aviation Regiment (consisting of some 18 aircraft, a mix of UH-60 Black Hawk helicopters, MEDEVAC configured Black Hawks, and CH-47 Chinook helicopters). Until 2006, the JSF and 1-228th Aviation Regiment were the only permanent party organizations. JSF consisted of approximately 21 permanent, 1-year tour, Air Force Security Forces personnel, including the Commander and the 1-228th consisted of approximately 55 permanent Army aviation personnel - pilots, crew chiefs, and aviation maintainers. The rest of the JSF personnel consisted of Army, Air Force, and U.S. Marines personnel who would be temporarily assigned to JSF rotating every 6-months. In that year, MEDEL, which was a U.S. Army-only unit, began receiving Air Force personnel, however it is no longer a joint billet. The requirement is for an U.S. Army Colonel to be the Commander of JTF-B and an U.S. Air Force Lieutenant Colonel to be the Deputy Commander. In addition, MEDEL is commanded by the U.S. Army, 1-228th AR is commanded by the U.S. Army, ARFOR is commanded by the U.S. Army, AFFOR is commanded by the U.S. Air Force, and JSF is commanded by the U.S. Air Force.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Vfr
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VLa base aérienne de Soto Cano (en anglais : Soto Cano Air Base, anciennement Palmerola Air Base) est une base aérienne conjointe de l'United States Air Force (forces aériennes des États-Unis) et de la force aérienne hondurienne, située à Palmerola, près de la base militaire de Comayagua, à 80 km de la capitale du Honduras. La base aérienne est devenue opérationnelle en 1981.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/abstract
p45
ssg8
(dp46
Vxml:lang
p47
Vpl
p48
sVtype
p49
Vliteral
p50
sVvalue
p51
VPort lotniczy Soto Cano (hiszp. Aeropuerto de Soto Cano; IATA: XPL, ICAO: MHJU) \u2013 wojskowy port lotniczy zlokalizowany w honduraskim mie\u015bcie Comayagua.
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/elevation
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#double
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V628.0
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/iataLocationIdentifier
p71
ssg8
(dp72
Vtype
p73
Vliteral
p74
sVvalue
p75
VXPL
p76
ssa(dp77
g7
(dp78
Vtype
p79
Vuri
p80
sVvalue
p81
Vhttp://dbpedia.org/ontology/icaoLocationIdentifier
p82
ssg8
(dp83
Vtype
p84
Vliteral
p85
sVvalue
p86
VMHSC
p87
ssa(dp88
g7
(dp89
Vtype
p90
Vuri
p91
sVvalue
p92
Vhttp://dbpedia.org/ontology/runwayDesignation
p93
ssg8
(dp94
Vtype
p95
Vliteral
p96
sVvalue
p97
V17/35
p98
ssa(dp99
g7
(dp100
Vtype
p101
Vuri
p102
sVvalue
p103
Vhttp://dbpedia.org/ontology/runwayLength
p104
ssg8
(dp105
Vdatatype
p106
Vhttp://www.w3.org/2001/XMLSchema#double
p107
sVtype
p108
Vtyped-literal
p109
sVvalue
p110
V2441.0
p111
ssa(dp112
g7
(dp113
Vtype
p114
Vuri
p115
sVvalue
p116
Vhttp://dbpedia.org/ontology/runwaySurface
p117
ssg8
(dp118
Vtype
p119
Vliteral
p120
sVvalue
p121
VAsphalt
p122
ssasVordered
p123
I01
ss.