(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VDouglass Residential College, located in New Brunswick, New Jersey, is a part of Rutgers, The State University of New Jersey. It is a non-degree-granting organization which succeeded the liberal arts Douglass College (originally New Jersey College for Women) when it was merged with the other undergraduate liberal arts colleges at Rutgers\u2013New Brunswick to form the School of Arts and Sciences in 2007. Female students enrolled at academic undergraduate schools at Rutgers\u2013New Brunswick, including the School of Arts and Sciences, School of Engineering, School of Environmental and Biological Sciences, School of Pharmacy, Mason Gross School of the Arts, etc., may participate in Douglass Residential College, at which they must satisfy additional requirements specific to the college.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Vfr
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VLe Douglass Residential College est une des composantes de l'université Rutgers. Cette entité propose un cursus de 4 ans centré sur la réussite féminine.Bien qu'aucun diplôme séparé ne soit offert, elle permet d'offrir de nombreuses opportunités aux jeunes femmes soucieuses de résider dans des ensembles exclusivement féminins, de participer à des associations féminines et de développer des compétences de leadership.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/numberOfStudents
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V2500
p52
ssasVordered
p53
I01
ss.