(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ves
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VLa Central Nuclear Bellefonte de la Tennessee Valley Authority está situada en Hollywood (Alabama). Los dos reactores de agua a presión de la planta fueron fabricados por Babcock and Wilcox. Se encuentran inacabados y en un estado de conservación desde 1988 después de una inversión de 6 millardos de dólares. El 22 de septiembre de 2005 se informó que Bellefonte había sido seleccionada como el emplazamiento para un reactor de agua presurizada AP-1000.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VThe Bellefonte Nuclear Generating Station (shortly BLN) was a partially constructed nuclear power plant located in Hollywood, Alabama. A total of four nuclear reactors (two originally; and two of new designs), had been proposed for the site, over a period of 40+ years. And 4.0+ billion dollars have been spent (constructing the preliminary plant infrastructure and ordering/delivering/installing major equipment items. But no nuclear reactor nor electric generating plant was ever nearly completed; and no nuclear fuel was delivered or loaded. Meaningful construction progress at the site site was halted in 1988, and all of the site's major, useable, delivered systems (power transformers, steam generators, cooling water pumps, etc.) have been removed from the site, and used at other electric generating stations, as part of an "asset recovery" program.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/abstract
p45
ssg8
(dp46
Vxml:lang
p47
Vde
p48
sVtype
p49
Vliteral
p50
sVvalue
p51
VDas unvollendete Kernkraftwerk Bellefonte bei der namensgebenden Insel Bellefonte im Tennessee River bei Scottsboro, Alabama sollte aus zwei Druckwasserreaktoren bestehen. Der Bau beider Blöcke wurde 1974 begonnen und 1988 gestoppt.
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/abstract
p58
ssg8
(dp59
Vxml:lang
p60
Vfr
p61
sVtype
p62
Vliteral
p63
sVvalue
p64
VLa centrale nucléaire de Bellefonte est une centrale située à Hollywood en Alabama qui appartient à Tennessee Valley Authority.
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/status
p71
ssg8
(dp72
Vtype
p73
Vliteral
p74
sVvalue
p75
VC
p76
ssasVordered
p77
I01
ss.