(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VBowman Gum Company was a Philadelphia-based manufacturer of bubble gum and trading cards in the period surrounding World War II founded by Jacob Warren Bowman. Originally known as Gum, Inc., the company produced a series of cards known as the "Play Ball" sets each year from 1939 to 1941. Production halted after the United States entered the war, and the company did not return to making baseball, football, and other sports-related trading cards until 1948, then under the Bowman name. In 1948, they were competing against Leaf Candy Company which left the marketplace in 1950, and in 1950 sold $1 million in baseball cards. For a few years, Bowman was the leading producer of baseball cards, but was overtaken by Topps Chewing Gum. After a period in which the two fought to sign players to exclusive contracts for their cards, Topps bought out Bowman in 1956 for $200,000. Much later, the Bowman brand was resurrected by Topps in 1989 to use on some of its subsidiary sports card sets. In recent years, the Bowman company has become known for being a top brand in making Rookie Cards.
p26
ssasVordered
p27
I01
ss.