(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/birthDate
p19
ssg8
(dp20
Vdatatype
p21
Vhttp://www.w3.org/2001/XMLSchema#date
p22
sVtype
p23
Vtyped-literal
p24
sVvalue
p25
V1984-7-3
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/Person/height
p32
ssg8
(dp33
Vdatatype
p34
Vhttp://dbpedia.org/datatype/centimetre
p35
sVtype
p36
Vtyped-literal
p37
sVvalue
p38
V188.0
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/abstract
p45
ssg8
(dp46
Vxml:lang
p47
Ven
p48
sVtype
p49
Vliteral
p50
sVvalue
p51
VDonnchadh Walsh (born 3 July 1984) is an Irish Gaelic footballer. A midfielder and forward, he plays his football with the Cromane club, the Mid Kerry divisional side and the Kerry county panel. Walsh was described as a 'star' and a 'teen sensation' for Kerry in the All-Ireland Minor Football Championship. He won the Munster Minor Football Championship with Kerry in 2001  and 2002. He was first selected for the senior squad in 2003. Despite his status as a highly promising player, Walsh did not make the breakthrough to All-Ireland Senior Football Championship football with Kerry until 2008. However, he was being tipped to do following an excellent 2007 season in the Kerry Senior Football Championship with Mid Kerry. He was also given his chance in the National Football League 2008. His first Munster Senior Football Championship game came in the final of July 2008. Walsh started and scored 1\u20131, but Cork defeated Kerry with a second-half comeback. The following year he won his first All-Ireland Senior Football Championship medal after Kerry beat Cork. Five years later Kerry defied all odds to claim their 36th All-Ireland in an amazing year and Walsh was exceptional throughout the whole season. But the one thing that eluded him was an All-Star. How he didn't win one between 2009-2014 was one of the most baffling mysteries in the GAA. Finally, in 2015, he got a fully deserved All-Star. His incredible work ethic when playing for kerry was finally rewarded.
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/activeYearsEndYear
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#gYear
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V2001
p65
ssa(dp66
g7
(dp67
Vtype
p68
Vuri
p69
sVvalue
p70
Vhttp://dbpedia.org/ontology/activeYearsStartYear
p71
ssg8
(dp72
Vdatatype
p73
Vhttp://www.w3.org/2001/XMLSchema#gYear
p74
sVtype
p75
Vtyped-literal
p76
sVvalue
p77
V2001
p78
ssa(dp79
g7
(dp80
Vtype
p81
Vuri
p82
sVvalue
p83
Vhttp://dbpedia.org/ontology/height
p84
ssg8
(dp85
Vdatatype
p86
Vhttp://www.w3.org/2001/XMLSchema#double
p87
sVtype
p88
Vtyped-literal
p89
sVvalue
p90
V1.88
p91
ssasVordered
p92
I01
ss.