(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VThe Housatonic River Railroad Bridge is a historic bridge carrying Metro-North Railroad's New Haven Line trackage across the lower Housatonic River in the U.S. state of Connecticut. It was listed on the National Register of Historic Places in 1987, and in its listing was described as also being referred to as Devon Bridge. It is also referred to as the Devon Railroad Bridge by the state Department of Environmental Protection. It is a "Scherzer Rolling Lift Bascule"-type bascule bridge. It has a steel superstructure and block stone piers. The moveable span is a Warren through truss span. The Connecticut River Railroad Bridge is another bridge of this type in Connecticut which is also NRHP-listed. It is one of eight moveable bridges on the Amtrak route through Connecticut surveyed in one multiple property study in 1986. The eight bridges from west to east are: Mianus River Railroad Bridge at Cos Cob, built in 1904; Norwalk River Railroad Bridge at Norwalk, 1896; Saugatuck River Railroad Bridge at Westport, 1905; Pequonnock River Railroad Bridge at Bridgeport, 1902; Housatonic River Railroad Bridge, at Devon, 1906; Connecticut River Railroad Bridge, Old Saybrook-Old Lyme, 1907; Niantic River Bridge, East Lyme-Waterford, 1907; and Thames River Bridge (Amtrak), Groton, built in 1919. The bridge is also used by Amtrak for its Northeast Corridor services.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/added
p32
ssg8
(dp33
Vdatatype
p34
Vhttp://www.w3.org/2001/XMLSchema#date
p35
sVtype
p36
Vtyped-literal
p37
sVvalue
p38
V1987-06-12
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/area
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#double
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V4046.86
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/nrhpReferenceNumber
p58
ssg8
(dp59
Vtype
p60
Vliteral
p61
sVvalue
p62
V87000842
p63
ssa(dp64
g7
(dp65
Vtype
p66
Vuri
p67
sVvalue
p68
Vhttp://dbpedia.org/ontology/yearOfConstruction
p69
ssg8
(dp70
Vdatatype
p71
Vhttp://www.w3.org/2001/XMLSchema#gYear
p72
sVtype
p73
Vtyped-literal
p74
sVvalue
p75
V1906
p76
ssasVordered
p77
I01
ss.