(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/Work/runtime
p19
ssg8
(dp20
Vdatatype
p21
Vhttp://dbpedia.org/datatype/minute
p22
sVtype
p23
Vtyped-literal
p24
sVvalue
p25
V159.0
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Vit
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VWelcome (Hindi: \u0935\u0947\u0932\u0915\u092e) è un film indiano del 2007 diretto da Anees Bazmee. Protagonisti del film sono Akshay Kumar, Feroz Khan, Nana Patekar, Anil Kapoor, Katrina Kaif, Malika Sherawat e Paresh Rawal. Il film è stato proiettato in India ed in diversi paesi nel mondo il 21 dicembre 2007, ed ha ricevuto una nomination ai Filmfare Awards nella categoria "Miglior attore non protagonista" (Anil Kapoor).
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/abstract
p45
ssg8
(dp46
Vxml:lang
p47
Ven
p48
sVtype
p49
Vliteral
p50
sVvalue
p51
VWelcome is a 2007 Indian Hindi-language masala comedy film directed by Anees Bazmee and produced by Firoz A. Nadiadwala and Ronnie Screwvala under the banner of UTV Motion Pictures. The film features a large ensemble cast of Akshay Kumar, Anil Kapoor, Nana Patekar, Katrina Kaif, Paresh Rawal, Malika Sherawat and Feroz Khan in his last film appearance, whilst Sunil Shetty makes a guest appearance and Malaika Arora Khan appears in an item number. The film spawned a sequel, named Welcome Back and became the first installment of Welcome film series. Welcome released worldwide on 21 December 2007, to mixed critical reviews and despite initial competition from Taare Zameen Par, was a strong financial success at the box office both in India and overseas. According to The Hindu, the film's climax scene is a rip-off from the Charlie Chaplin film, The Gold Rush and Michael Madana Kama Rajan.
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/runtime
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#double
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V9540.0
p65
ssasVordered
p66
I01
ss.