(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VThe Better Show was a syndicated lifestyle and celebrity focused daytime talk show. It aired weekdays on 160 stations across the United States. The program was produced and distributed by Meredith Corporation. The Better Show got its name from and is based on Meredith's flagship publication, Better Homes and Gardens. The show also tapped its other magazine's expert's in home, shelter and parenting. This was not Better Homes and Gardens' first foray into television; in the 1990s, the magazine presented a similar syndicated weekly series, Better Your Home with Better Homes and Gardens. In addition, the Australian version of the magazine has their TV series as well. The hour-long daytime strip show Better allows eight minutes of local content. While in Kansas City, the national version on KSMO-TV was also compliment by a total localized version, Better Kansas City, on KCTV. At least with Meredith stations those with some localized content gave a local version of the name. For example, WNEM-TV's version was called Better Mid-Michigan. while WGCL-TV's edition was known as Better Mornings Atlanta; and KPHO-TV's show was called Better Arizona. WPHL-TV (a Tribune-owned Better affiliate) aired the national version in the morning with local cut-ins throughout the hour, branded as Better Philly.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/numberOfSeasons
p32
ssg8
(dp33
Vdatatype
p34
Vhttp://www.w3.org/2001/XMLSchema#nonNegativeInteger
p35
sVtype
p36
Vtyped-literal
p37
sVvalue
p38
V7
p39
ssasVordered
p40
I01
ss.