(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Ven
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VTuroa is a large skifield on the south western side of Mount Ruapehu, the highest mountain in the North Island of New Zealand, in Tongariro National Park. The area has been used for skiing since before the completion of the Mountain Road, but the first lifts opened in 1978. There are two beginner areas, and many intermediate and advanced trails. The upper field is a mix of natural pipes, steep drops, fast plains, and easier slopes, along with several terrain parks. The lower field contains the field's single narrow beginner trail, Clarry's Track, and a few other intermediate trails. They also serve as access to the base area from the upper mountain, and are often crowded. The field is 500 hectares (1,200 acres) and has a 722 metres (2,369 feet) vertical drop. The skifield is reached via the Mountain Road from the town of Ohakune. The Mountain Road was built by locals from Ohakune, mostly during weekends after they formed the Mountain Road Association in 1952. Their aim was to open Ruapehu's southern slopes for skiing, partly as a replacement industry for the decline in logging which had sustained the town for the previous decades. The now renamed Ministry of Works helped with the road on one occasion by 'misplacing' a culvert destined for another roading project. The 17 kilometre road was opened in 1963. It winds up through spectacular native forest before breaking out above the tree line and finishes at a complex of carparks below the bottom chairlift. Turoa has been owned by Ruapehu Alpine Lifts since 2000, which also owns the nearby Whakapapa skifield, also on Mt. Ruapehu. It is possible to traverse from one field to the other. The two are operated together, with a combined lift ticket for both fields. Together, they are considered to be the largest ski resort in New Zealand and possibly the southern hemisphere. On a good day it is possible to hike to the top of the mountain with skis or snowboard in hand, view the Crater Lake, and then ski back down to the field, or to Whakapapa. Also on a clear day Mount Taranaki can be seen. A new high speed six-seater chairlift has been added for the winter of 2007, replacing an existing T-bar to the top of the mountain.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/areaTotal
p32
ssg8
(dp33
Vdatatype
p34
Vhttp://www.w3.org/2001/XMLSchema#double
p35
sVtype
p36
Vtyped-literal
p37
sVvalue
p38
V4.99787e+06
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/maximumElevation
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#double
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V2322.0
p52
ssa(dp53
g7
(dp54
Vtype
p55
Vuri
p56
sVvalue
p57
Vhttp://dbpedia.org/ontology/minimumElevation
p58
ssg8
(dp59
Vdatatype
p60
Vhttp://www.w3.org/2001/XMLSchema#double
p61
sVtype
p62
Vtyped-literal
p63
sVvalue
p64
V1600.0
p65
ssasVordered
p66
I01
ss.