(dp0
Vhead
p1
(dp2
Vlink
p3
(lp4
sVvars
p5
(lp6
Vp
p7
aVo
p8
assVresults
p9
(dp10
Vdistinct
p11
I00
sVbindings
p12
(lp13
(dp14
g7
(dp15
Vtype
p16
Vuri
p17
sVvalue
p18
Vhttp://dbpedia.org/ontology/abstract
p19
ssg8
(dp20
Vxml:lang
p21
Vpt
p22
sVtype
p23
Vliteral
p24
sVvalue
p25
VR-16 Korea é uma competição anual e um festival cultural de breakdance organizado pela Korea Tourism Organization e pelo Governo da Coreia do Sul. O principal evento reúne dezesseis crews de quinze países diferentes que disputam dois títulos: melhor performance e batalha de crews. O festival também conta com grafiteiros e músicos de hip hop.
p26
ssa(dp27
g7
(dp28
Vtype
p29
Vuri
p30
sVvalue
p31
Vhttp://dbpedia.org/ontology/abstract
p32
ssg8
(dp33
Vxml:lang
p34
Ven
p35
sVtype
p36
Vliteral
p37
sVvalue
p38
VR16 Korea is an annual international b-boy tournament and urban arts cultural festival sponsored primarily by the Korea Tourism Organization and the South Korean Ministry of Culture, Sports and Tourism. The main event features sixteen B-Boy crews representing fifteen countries competing in a two day tournament for world championship titles in two categories: best crew performance and best crew battle. The festival features graffiti artists, street wear designers, musical performers and dancers who specialize in hip-hop, popping, locking and other urban arts subcultures from South Korea and other countries. Created and Organized by Korea Tourism Organization produced by Cartel Creative Inc., R16 is a celebration of the creative energy behind urban youth culture. Based on a theme of "Respect" (which is what the "R" in R16 refers to), the tournament and festivals were first held in 2007 in the city of Seoul. The 2008 event took place in the city of Suwon The 2009 event host is the Metropolitan City of Incheon and the 2010 event was brought back to Seoul City. The event will continue annually, as the Hip Hop culture has recognized South Korean b-boys as a special part of its history. Korean-American b-boy, singer, and rapper, Jay Park, has been the official ambassador of R16 for years 2011, 2012, and 2013. Since 2014, R-16 Korea partnered up with the World BBoy Series and helped create Undisputed, an event to crown the solo world bboy champion.
p39
ssa(dp40
g7
(dp41
Vtype
p42
Vuri
p43
sVvalue
p44
Vhttp://dbpedia.org/ontology/year
p45
ssg8
(dp46
Vdatatype
p47
Vhttp://www.w3.org/2001/XMLSchema#gYear
p48
sVtype
p49
Vtyped-literal
p50
sVvalue
p51
V2007
p52
ssasVordered
p53
I01
ss.